# Dockerfile
FROM nikolaik/python-nodejs:latest

# Install pip
RUN apt-get update && apt-get install -y python3-pip

# Install Git
RUN apt-get update && apt-get install -y git

RUN apt-get install -y postgresql-client